apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-config
  namespace: frontend
data:
  # URL: "http://backend-service.backend.svc.cluster.local:3001"
  REACT_APP_BACKEND_URL: "http://localhost:3001"
