apiVersion: v1
kind: Secret
metadata:
  name: frontend-secret
  namespace: frontend
type: Opaque
data:
  # Data needs to be converted to base64
  # REACT_APP_BACKEND_URL: http://localhost:3001
  REACT_APP_BACKEND_URL: aHR0cDovL2xvY2FsaG9zdDozMDAx  
