apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
spec:
  type: NodePort
  selector:
    app: {{ .Values.app.name }}
  ports:
  - protocol: TCP
    port: {{ .Values.app.image.containerPort }}
    targetPort: {{ .Values.app.image.containerPort }}
    nodePort: {{ .Values.app.nodePort }}
