apiVersion: v1
entries:
  flaskapp:
  - apiVersion: v2
    appVersion: 1.16.0
    created: "2024-08-18T19:24:46.6061228+05:30"
    description: Flask App Chart
    digest: 37bf3ba74f0eff5b4ddeade2d8e6fed0f5b1251ce7178486a77047cc269c8b19
    name: flaskapp
    type: application
    urls:
    - https://pkhelm.s3.amazonaws.com/flaskapp-0.1.0.tgz
    version: 0.1.0
generated: "2024-08-18T19:24:46.602279+05:30"
